### ISSUE TITLE
ruby 2.0.0p598 compatibility

### ISSUE THREAD

**Issue by BusyByte** [benkiefer/maven-helper-script#1]
This script appears to only work with Ruby 1.9.x.
Ruby 1.9 is end of life.
Can you upgrade this to work with Ruby 2.0.x?
I ran into issues with the yaml not being installed in ruby by default and configuration_checker blows up on "@yml['commands'].each do |phase|" saying it can not find the each method on nil

**Comment by benkiefer** [comment]
I actually forgot people were using this thing. I will take a look at upgrading it and give you some sort of timeline tonight. Thanks @BusyByte!

**Comment by benkiefer** [comment]
I've released version 0.2.0, and it is working well for me on fedora 21 with rvm 1.26.11 and ruby 2.2.2 (which should be the latest of everything).

I went ahead and did a custom gemset with rvm so that I was nice and clean, but please let me know if you guys are having any problems!

Thanks again for reporting.

**Comment by benkiefer** [comment]
Closing this down.
